In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from implementations import *
from proj1_helpers import *
from preprocessing import *
%load_ext autoreload
%autoreload 2

## Load the training data into feature matrix, class labels, and event ids:

In [2]:
DATA_TRAIN_PATH = '../data/train.csv' # TODO: download train data and supply path here 
y_train, tx_train, ids_train = load_csv_data(DATA_TRAIN_PATH)

In [ ]:
print(ids_train)
tx_train.shape
#250000 data points, 30 features per data point.

#### Early exploration 
**Goal : making sure the basic functions work, testing unchanged vs normalized input data


In [3]:
#Initializing weights, sampling data
w0 = np.random.randn(tx_train.shape[1],1)
#Sampling a few datapoints out of the 250000
n_samples = 5000

y_tr_sampled, tx_tr_sampled = sample_data(y_train,tx_train,n_samples)
y_tr_norm, tx_temp = sample_data(y_train,tx_train,n_samples)
#standardizing the input
tx_tr_norm, _, _ = standardize(tx_temp)


In [27]:
#Using SGD
w_sampled_sgd, loss_sampled_sgd = least_squares_SGD(y_tr_sampled, 
                                           tx_tr_sampled,
                              w0, 500, 1e-7)

w_norm_sgd, loss_norm_sgd = least_squares_SGD(y_tr_norm, tx_tr_norm,
                              w0, 300, 1e-2)
print("sgd normal tx, loss:",loss_sampled_sgd,"\n",w_sampled_sgd[0:3])
print("sgd std tx, loss: ", loss_norm_sgd,"\n",w_norm_sgd[0:3])
#print(w_norm_test[0:10])

sgd normal tx, loss: 3196.463945095456 
 [[ 0.01890528]
 [ 0.41740932]
 [-0.176445  ]]
sgd std tx, loss:  0.5520143028253306 
 [[ 0.26417737]
 [ 0.40882269]
 [-0.1338973 ]]


In [11]:
#Using GD
w_sampled_gd, loss_sampled_gd = least_squares_GD(y_tr_sampled,
                                                tx_tr_sampled,
                                                w0, 300,1e-7)
w_norm_gd, loss_norm_gd = least_squares_SGD(y_tr_norm, tx_tr_norm,
                              w0, 500, 1e-2)
print("gd normal tx, loss:",loss_sampled_gd,"\n",w_sampled_gd[0:3])
print("gd std tx, loss: ", loss_norm_gd,"\n",w_norm_gd[0:3])

gd normal tx, loss: 4359.76458056838 
 [[ 0.01597099  0.01600354  0.01597099 ...  0.01600354  0.01597099
   0.01600354]
 [ 0.4106628   0.41035555  0.4106628  ...  0.41035555  0.4106628
   0.41035555]
 [-0.18392441 -0.18447188 -0.18392441 ... -0.18447188 -0.18392441
  -0.18447188]]
gd std tx, loss:  0.5094346330947049 
 [[ 0.19303652]
 [ 0.37707852]
 [-0.20378363]]


In [34]:
#Using normal eq
n_samples = 200000

y_normal, temp = sample_data(y_train,tx_train,n_samples)
#standardizing the input
tx_normal, _, _ = standardize(temp)
w_normal, loss_normal = least_squares(y_train,tx_train)
print("LS normal eq, loss:",loss_normal,"\n",w_normal[0:3])

w_ridge, loss_ridge = ridge_regression(y_train,tx_train,5e-4)
print("LS normal eq, loss:",loss_ridge,"\n",w_ridge[0:3])


LS normal eq, loss: 0.3396868094770356 
 [ 8.03494347e-05 -7.20202267e-03 -6.05417273e-03]
LS normal eq, loss: 0.33968938634802587 
 [ 8.21350623e-05 -7.21942061e-03 -6.00961895e-03]


In [12]:
DATA_TEST_PATH = '../data/test.csv' # TODO: download test data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)
tX_test.shape, ids_test.shape

((568238, 30), (568238,))

In [38]:
OUTPUT_PATH = '../output/' # TODO: fill in desired name of output file for submission

#Creating the submissions for each method of 
y_pred_gd = predict_labels(w_norm_gd, tX_test)
y_pred_sgd = predict_labels(w_norm_sgd,tX_test)
y_pred_normal = predict_labels(w_normal,tX_test)
y_pred_ridge = predict_labels(w_ridge,tX_test)
create_csv_submission(ids_test, y_pred_sgd,
                      OUTPUT_PATH+"submission_sgd.csv")
create_csv_submission(ids_test, y_pred_gd, 
                      OUTPUT_PATH+"submission_gd.csv")
create_csv_submission(ids_test, y_pred_normal,
                      OUTPUT_PATH+"submission_normaleq.csv")
create_csv_submission(ids_test, y_pred_ridge,
                      OUTPUT_PATH+"submission_ridge.csv")