In [28]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from implementations import *
from proj1_helpers import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Load the training data into feature matrix, class labels, and event ids:

In [8]:
DATA_TRAIN_PATH = '../data/train.csv' # TODO: download train data and supply path here 
y_train, tX_train, ids_train = load_csv_data(DATA_TRAIN_PATH)

In [9]:
print(ids_train)

[100000 100001 100002 ... 349997 349998 349999]


#### Early exploration 
**Goal : making sure the basic functions work, without pre-processing the data**

In [34]:
tX.shape
#250000 data points, 30 features per data point.

(250000, 30)

In [63]:
w0 = np.zeros((tX.shape[1],1))
w_norm = np.random.normal(0,0.1,(tX.shape[1],1))
#taking only a few subsets of the data (slicing 0:5)
w_test, _ = least_squares_SGD(y[0:200], tX[0:200], w0, 300, 1e-7)
w_norm_test, _ = least_squares_SGD(y[0:200], tX[0:200], w_norm, 300, 1e-7)

In [66]:
print(w_test[0:10])
print(w_test.shape)
print(w_norm_test[0:10])

[[ 2.18086510e-04]
 [-2.63983322e-04]
 [-1.55659179e-04]
 [ 2.63711106e-05]
 [-1.00250558e-04]
 [ 2.30175377e-06]
 [-9.36287529e-05]
 [ 9.75675772e-07]
 [-2.86911734e-05]
 [ 1.23513616e-04]]
(30, 1)
[[ 0.00502809]
 [ 0.03249152]
 [-0.03755108]
 [-0.06297395]
 [-0.06131285]
 [-0.00895155]
 [ 0.08680313]
 [-0.05298526]
 [ 0.04904228]
 [ 0.07986389]]


## Generate predictions and save ouput in csv format for submission:

In [65]:
DATA_TEST_PATH = '../data/test.csv' # TODO: download test data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)
tX_test.shape, ids_test.shape

((568238, 30), (568238,))

In [67]:
OUTPUT_PATH = '../output/submission.csv' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(w_test, tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)

In [78]:
len(y_pred[np.isin(y_pred,1)])
len(y_pred[np.isin(y_pred,-1)])

11813